global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['demo-rabbitmq:15692']
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['demo-nginx-exporter:9113']
  - job_name: 'go-api'
    static_configs:
      - targets: ['demo-api:8080']



# docker cp .\prometheus.yml prometheus:/etc/prometheus/prometheus.yml
